### ISSUE TITLE
Stripe requesting migration to stripe connect

### ISSUE THREAD

**Issue by mnights101** [BNBFuse/milestones#47]
Manik,

Stripe is requesting we adjust our platform to stripe connect They wrote:

> Hi ,

Thank you for getting back to us with that information; my name is Russell and I'm working with Nora on your case.

We've gone ahead and returned your account to good standing, however in order for us to continue supporting your business, we'll need you to implement Stripe Connect. Without Connect, your business model would be considered aggregation as you're collecting payments for multiple listings on your rental platform.

It is very important to us that we see your 3rd parties get the revenue share they are entitled to and avoid obscuring of the flow of funds. Our policy against aggregation is firm and doesn't allow any exceptions. That said, to ensure processing for your account doesn't cease in the future we'll need you to integrate Stripe Connect. You can learn more about Stripe Connect at the link below:

https://stripe.com/connect 

Please let me know if you have any questions about this, or anything else.

Best,

/> Russell

**to complete this task please please perform the following:**

- [x] Advice me on what connect account type is best to select in order to control time of payout as we do with paypal: https://stripe.com/connect/account-types

- [x] Integrate & Design Host onboarding flow to collect staggered data to comply with stripe required data and credentials.

- [x] Configure timed payouts after checkin date

- [x] Add Send Money to debit card feature: https://stripe.com/blog/send-money-to-debit-cards

- [ ] configure refunds to comply with refund policies.

- [x]  after implementation and flow is complete, we will decide what stripe account all currently uploaded properties will use and apply as default.

- [ ]  make sure that when a refund occurs, it is a partial refund less gateway fees which are non-refundable.

Please quote and issue ETA. Thanks..

**Comment by mindrootstech** [comment]
Most of the requirements are clear but i've written to Stripe for clarification on the delayed transfer to the host.
Once they come back on it, i'll update you with the cost and ETA.

**Comment by mindrootstech** [comment]
Hey Marco,

So here is the final solution:
We will implement Stripe Connect with Express accounts.
Each host will have to activate credit cards payment like crypto.
If he does, he will have to go through the stripe on-boarding process where he/she will neter their bank account/debit card details to getpayouts and get connected to stripe.

For payouts, we will use Stripe connect split payments where host payout will be delayed by the number of days left for check-in. This means money will be immediately tranferred to his stripe account but wont be avaialable for payout till the day of Check-in. Since stripe allows a max of 90 days for delayed payments, we will have to put a check that bookings cannot happen beyond 90 days.

Refunds will also work acc to Stripe connect and our platform (same as in case of Paypal).

Total effort to implement this will be $450.

Also, just to let you know, Stripe connect charges $2 per month for each active connected account (https://stripe.com/us/connect/pricing). So, let me know if you want to charge the hosts any additional fee in case of Stripe to cover for the $2.

Please confirm so we can start off work.

**Comment by mnights101** [comment]
Manik,

This sounds good, but it must occur in sandbox , not on live site.
Also, be sure to use stripes UI onboarding sample and let me know if we can debit the clients stripe account for the monthly fee to cover the costs?

Thanks

**Comment by mindrootstech** [comment]
Do we have a sandbox setup of the site somewhere?
Yes, we will use the Stripe onboarding process.

For the fee, you will only be charged if the client recieves a payment. So we can embed the cost in the booking amount to cover it rather than separately charging them.

**Comment by mindrootstech** [comment]
Sure. I will check and if we can, will set it that ways.

**Comment by mnights101** [comment]
issue paid out via upwork milestone 16
